apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynapp-rs-fortune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynapp-rs-fortune
  template:
    metadata:
      labels:
        app: mynapp-rs-fortune
    spec:
      containers:
      - name: web-server
        image: nginx:alpine
        volumeMounts:
        - name: web-fortune
          mountPath: /usr/share/nginx/html
          readOnly: true
        ports:
        - containerPort: 80

      - name: html-generator
        image: c1t1d0s7/fortune   # 3초마다 내용(htdocs)을 덮어쓰는 이미지
        volumeMounts:
        - name: web-fortune
          mountPath: /var/htdocs

      volumes:
      - name: web-fortune
        emptyDir: {}