apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynapp-rs-exp
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values: 
      - mynapp-rs-exp
  template:
    metadata:
      labels:
        app: mynapp-rs-exp
    spec:
      containers:
      - name: mynapp
        image: c1t1d0s7/myweb
        ports:
        - containerPort: 8080
